version: "3.3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: ${POSTGRES_NAME}
    hostname: ${POSTGRES_NAME}
    ports:
      - ${POSTGRES_EXPOSE_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - '${POSTGRES_DATA_DIR}:/var/lib/postgresql/data'
    # networks:
    #   - postgres-network
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    image: ${APP_NAME}
    restart: always
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=${ENV_NAME}
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=UTC
      - TZ=UTC
    ports:
      - ${APP_EXPOSE_PORT}:${APP_PORT}
    depends_on:
      - postgres
    # networks:
    #   - postgres-network

# networks:
  # postgres-network:
  #   driver: bridge
